basePath: /
definitions:
  handlers.errorResponse:
    properties:
      message:
        type: string
    type: object
  models.TodoModel:
    properties:
      completed:
        example: false
        type: boolean
      created_at:
        example: "2023-05-23T08:00:00Z"
        type: string
      description:
        example: This is a sample todo item
        type: string
      id:
        example: 1
        type: integer
      title:
        example: Sample Todo
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for Todo App
  title: Todo App API
  version: "1.0"
paths:
  /todos:
    get:
      consumes:
      - application/json
      description: Returns a list of all todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TodoModel'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      summary: Get all todos
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: Creates one new todo
      parameters:
      - description: Todo Model
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.TodoModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.TodoModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      summary: Create a new todo
      tags:
      - todos
  /todos/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes an existing todo by id
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      summary: Delete todo by ID
      tags:
      - todos
    get:
      consumes:
      - application/json
      description: Returns one todo by id
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TodoModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      summary: Get todo by ID
      tags:
      - todos
    patch:
      consumes:
      - application/json
      description: Updates an existing todo by id
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      - description: Todo Model
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.TodoModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TodoModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      summary: Update an existing todo
      tags:
      - todos
swagger: "2.0"
